---
title: "BBC_LIST_OF WRAPPERS"
author: "christopher okoth"
date: "4/17/2020"
output: html_document
---
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
polls <- read.csv(file.choose())
rankings <- read.csv(file.choose())
```
# Just set the fonts beforehand 

```{r include=FALSE}
windowsFonts(Harrington = windowsFont('Harrington'),
             Papyrus = windowsFont('Papyrus'),
             Gabriola = windowsFont('Gabriola'))
```


### Let us plot the highest ranked song by year
```{r echo=TRUE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}

rankings %>% select(artist,title,year,points,gender) %>% group_by(year) %>% #then we return 1 row for each group based on points
  top_n(1,points) %>% arrange(desc(year)) %>% mutate(song=paste(artist,"-",title))->top_songs_by_year


top_songs_by_year %>% ggplot(mapping=aes(x=year,y=points,label=song,fill=points))+geom_col()+
  scale_fill_gradient2(high = "cyan2",low = "midnightblue",mid="plum2",midpoint = 60)+
  ggdark::dark_theme_classic()+
  ggtitle("HIGHEST RANKED SONGS BY YEAR")+labs(x="YEAR",caption = "@christopherokoth")+theme(plot.title = element_text(family ='Papyrus',color = "lightgoldenrodyellow" ,size = 20,face = "bold"))->plot1

plotly::ggplotly(plot1)
#plotly::ggplotly(plot1,tooltip=c("x","y","label"))

```
### Then I just set the fonts I want to use in this analysis visuals


### The plot of Highest ranked songs with focus to females...just a gganotate practice 
## The cordinated for the locations can be created to prevent the trial and error and counting approach 

```{r echo=TRUE, fig.width=14, message=FALSE, warning=FALSE, r,fig.height=7}

####Top ranked songs with focus on females
text1 <- "MC Lyte - first Hiphop Female artist\n to be nominated for a Grammy\nunder Best Rap Single(Song - 'Rucffneck')"
text2 <- "Queen Latifah - released hiphop\n hit 'UNITY' addressing\ndomestic violence, street harassment ..."
text3 <- "Missy Elliot - Wins her\nFirst Grammy Awards\n[song: Get Ur Freak On]"
text4 <- "Cardi B - Wins several categories\n in BET Awards - Her Single\n 'Bodak Yellow' doesn't win\n Hiphop video [Dj Khaled wins]"
text5 <- "Lauryn Hill's Album\n[The Miseducation of Lauryn Hill#5]\n top-TEN highest first-week\n home market sales"
#rankings %>% filter(stringr::str_detect(gender,"female"),points>7)


rankings %>% group_by(year,gender) %>% summarise(mean_points=mean(points)) %>% arrange(desc(mean_points)) %>% 
  ggplot(aes(factor(year),mean_points,fill=gender))+geom_col()+ggsci::scale_fill_startrek()+
    geom_text(aes(14,55), label = text1, family = 'Gabriola', hjust = -0.05, vjust = 1, size = 5, color = "#bada55")+
  geom_segment(aes(x=14,xend=14,y=55,yend=30), arrow = arrow(length = unit(0.1,'in')), size = 1.5, col = '#bada55')+
  geom_text(aes(19,34),label=text5,family="Papyrus",color="navy")+
  geom_segment(aes(x=19,xend=19,y=25,yend=30),arrow = arrow(length = unit(0.1,"in")),size=1.6,color="navy")+
  geom_text(aes(26.3,30),label=text3,color="orange")+
  geom_segment(aes(x=25,xend=23,y=31,yend=31),arrow = arrow(length = unit(0.1,"in")),size=1.6,color="orange")+
  geom_text(aes(38,26),label=text4,color="grey0")+
  geom_segment(aes(x=38,xend=36,y=26,yend=16),arrow = arrow(length = unit(0.1,"in")),size=1.6,color="grey0")+
  ggthemes::theme_economist()
```


